エネミーの追加
tricore-as17/scrollShotGame2.5D pull request #10
Opened 2024-06-12 03:03 UTC by tricore-as17

追加したもの
　・横移動するだけのエネミーを1体増加
　・左方向に弾を撃つだけの敵を2体新規で追加
　・弾を撃つ敵を追加したことでshotManagerの変更それにともなうPlayerの変更を行いました。

ShotManagerを変更した理由
　もともと弾を撃っていたのがPlayerだけだったのでShotManagerに弾の撃つ間隔を管理させていたのですが、それだとVector
　で管理しているEnemyを追加した際にどのキャラの弾の間隔を管理しているかが判断できなくなったので、Player,Enemyなど
　個々で管理するようにしました。
　
変更の範囲が広くなって今って申し訳ございません。

2024-06-13 01:05 UTC, tricore-as03 requested changes

2024-06-13 01:05 UTC, tricore-as03 commented on GameProject/LeftShotEnemy.cpp
> +    damage = INIT_DAMAGE;
[MUST]
ほとんど`EasyEnemy`と内容が似ているので`BaseEnemy`側にまとめられないでしょうか？

2024-06-13 01:09 UTC, tricore-as07 requested changes

2024-06-13 01:09 UTC, tricore-as07 commented on GameProject/BaseEnemy.cpp
> +void BaseEnemy::CountShotInterval(const int INTERVAL_RIMIT)
[MUST]
ここのINTERVAL_RIMITは定数というより引数としての扱い方の方が意味合いが強く、
またほかのconstを使った引数の箇所はlowerCamelCaseになっているのでここも統一してください。

2024-06-13 01:09 UTC, tricore-as07 commented on GameProject/BaseEnemy.h
> +	int** graph;		    //画像
[Q]
ここはなんのためにポインタのポインタを扱っているのでしょうか？

2024-06-13 01:09 UTC, tricore-as07 commented on GameProject/LeftShotEnemy.h
> +    static constexpr float W = 1.45f;       //幅
[MUST]
ここの省略表記はさすがに意味が伝わらないです

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/EnemyManager.cpp
> +    for (int i = 0; i < EAZY_NUM;i++)
誤字修正しました！

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/EnemyManager.cpp
> +    leftShotEnemy[1]->Init(VGet(LEFT2_FIRST_X, LEFT2_FIRST_Y, 0));
初期化する値が違うため共通化処理がうまくできませんでした。
csvファイルから初期化する値を読み込んで共通化するようにしようと思います。
csvの対応は別のプルリクエストで行います。

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/LeftShotEnemy.cpp
> +    damage = INIT_DAMAGE;
BaseEnemyで全く同じ内容の部分とpositionを初期化して、それを継承先で呼ぶ形に変更しました。

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/BaseEnemy.cpp
> +void BaseEnemy::CountShotInterval(const int INTERVAL_RIMIT)
申し訳ございません。持ってくる値が定数だったのでつられて定数の形にしてました！
lowerCamelCaseに修正しました

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/BaseEnemy.h
> +	int** graph;		    //画像
敵を2次元の画像で表示しようと思っていてその際に前のゲームで下記のように配列を用意していたので
まだ使っていませんが準備していました。

	//画像のメモリを確保
	graph = new int* [4];
　　//それぞれのアニメーションのコマ数によって配列を用意
	graph[RUN] = new int[GTAPH_SPRIT_NUM_WALK];		       //歩き
	graph[JUMP] = new int[GRAPH_SPRIT_NUM_JUMP];		       //ジャンプ
	graph[FALL] = new int[GRAPH_SPRIT_NUM_FALL];			//落下中
	graph[HIT] = new int[GRAPH_SPRIT_NUM_HIT];				//ヒット時

2024-06-13 22:49 UTC, tricore-as17 commented on GameProject/LeftShotEnemy.h
> +    static constexpr float W = 1.45f;       //幅
申し訳ございません。たしかにこれじゃ意味が伝わりませんでした！
widthとheightに修正しました。

2024-06-14 00:37 UTC, tricore-as03 commented on GameProject/EnemyManager.cpp
> +    leftShotEnemy[1]->Init(VGet(LEFT2_FIRST_X, LEFT2_FIRST_Y, 0));
（メモ）口頭で詳細把握済み

2024-06-14 00:42 UTC, tricore-as03 approved these changes
LGTM

2024-06-14 00:46 UTC, tricore-as07 commented on GameProject/BaseEnemy.h
> +	int** graph;		    //画像
まだ使わないものは基本的にPRに含めないほうがいいですね
何かしらのやむを得ない理由がある場合は必ずコメントを残すようにしましょう

2024-06-14 00:48 UTC, tricore-as07 commented on GameProject/BaseEnemy.cpp
> +void BaseEnemy::CountShotInterval(const int INTERVAL_RIMIT)
修正が反映されていないようです

2024-06-14 01:09 UTC, tricore-as07 approved these changes
LGTM

2024-06-14 01:11 UTC, merged