関数や変数の命名を修正しました
tricore-as17/scrollShotGame2.5D pull request #11
Opened 2024-06-13 00:53 UTC by tricore-as17

変更したもの
　・略称から正式名称
　　・pos→position
　　・dir→dirction
　　・init→initialize
　・命名自体の変更
　　・check→is,can
　　

2024-06-13 02:23 UTC, tricore-as03 requested changes

2024-06-14 00:53 UTC, tricore-as17 commented on GameProject/EasyEnemy.cpp
> +void EasyEnemy::Update(const Map& map,const VECTOR&cameraPosition,ShotManager& shotManager)
間を空ける修正をしまいた！

2024-06-14 00:53 UTC, tricore-as17 commented on GameProject/Colision.cpp
> +    auto downPositionY = VGet(objectPosition.x, objectPosition.y - Map::ONE_PIXEL_SIZE, objectPosition.z);
footPositionで修正しました！

2024-06-14 02:04 UTC, merged

2024-06-14 02:08 UTC, tricore-as03 reviewed
LGTM