エネミーの情報をcsvから持ってくるように変更
tricore-as17/scrollShotGame2.5D pull request #15
Opened 2024-06-17 07:06 UTC by tricore-as17

追加したもの
　・CSVファイルの内容をまとめたinformationクラス
　・CSVファイルの内容を読み込むLoad関数をEnemyManagerに追加

2024-06-17 10:23 UTC, tricore-as03 requested changes

2024-06-17 10:23 UTC, tricore-as03 commented on GameProject/EnemyManager.cpp
> +        }
[MUST]
必ずどちらかのif文にしか入らないので、else ifにしてください。
「else if = どちらかにしか入らない」が一目で分かるようになります。

2024-06-17 10:23 UTC, tricore-as03 commented on GameProject/EnemyManager.cpp
> +        enemyInformation.emplace_back(new EnemyInformation(information));
[MUST]
`enemyInformation`は敵の生成時にしか必要ないと思うので、わざわざメンバ変数として持たせる必要はないかと。
`LoadEnemyInformation`の戻り値で受け取るようにし、コンストラクタで生成が完了したら、そのままdeleteで破棄してしまってよいかと。

2024-06-17 14:22 UTC, tricore-as17 commented on GameProject/EnemyManager.cpp
> +        enemyInformation.emplace_back(new EnemyInformation(information));
たしかに無駄にメンバ変数を用意する形になっていました！戻り値で渡す形に変更しました！

2024-06-17 14:22 UTC, tricore-as17 commented on GameProject/EnemyManager.cpp
> +        }
しっかり意識できていませんでした！else ifに修正しました！

2024-06-18 01:41 UTC, tricore-as03 approved these changes
LGTM

2024-06-18 01:56 UTC, merged