UIの追加
tricore-as17/scrollShotGame2.5D pull request #18
Opened 2024-06-20 04:50 UTC by tricore-as17

追加したもの
　・タイトル画面の追加(１枚の画像と説明文)
　・プレイヤーの体力を表示するUIの追加
　・ゲーム中の背景をスカイドームで追加

2024-06-20 05:30 UTC, tricore-as03 requested changes

2024-06-20 05:30 UTC, tricore-as03 commented on GameProject/BackGround.cpp
[Q]
背景画像１枚の管理にクラスを用意したのは何故でしょうか？
`GameScene`でしか使っていないようなので、単純に`GameScene`で画像ハンドルを持つだけではダメなのでしょうか？

2024-06-20 05:30 UTC, tricore-as03 commented on GameProject/BaseUI.cpp
> +void BaseUI::CountBlinkingString()
[Q]
`CountBlinkingString`は`TitleUI`でしか使ってないようですが、`BaseUI`にあるのは何故でしょうか？

2024-06-20 05:30 UTC, tricore-as03 commented on GameProject/Font.cpp
> +    LPCSTR SuimenjiFontName = "水面字04";
[MUST]
画面で表示する文字列以外でプログラムが参照する値に日本語を使うのはよくないです。
英語で名前を付けるようにしてください。

2024-06-20 05:30 UTC, tricore-as03 commented on GameProject/Game.cpp
> +    font = new Font();
[MUST]
恐らく`Font`クラスはUIでしか使わないと思うので、UIクラスでnewしてしまってよいかと。

2024-06-21 01:53 UTC, tricore-as17 commented on GameProject/Game.cpp
> +    font = new Font();
確かにゲームからわざわざ引数で渡しているのも無駄な処理でした！
UIクラスで持つように変更しました！

2024-06-21 01:53 UTC, tricore-as17 commented on GameProject/Font.cpp
> +    LPCSTR SuimenjiFontName = "水面字04";
申し訳ございません。フォント自体の名前が日本語になっていて変更が出来ないみたいなので、このままでいこうと思います。

2024-06-21 01:53 UTC, tricore-as17 commented on GameProject/BaseUI.cpp
> +void BaseUI::CountBlinkingString()
Baseクラスを削除して新しく点滅用のクラスを作り、メンバクラスにしてそこで処理するように変更しました。

2024-06-21 01:53 UTC, tricore-as17 commented on GameProject/BackGround.cpp
他に3Dのモデルなどを背景として動かしたりするときのために一応作っておいたのですが、明確に作る予定があるわけでは無いのでgameSceneに持たせようと思います！

2024-06-21 02:47 UTC, tricore-as03 approved these changes
LGTM

2024-06-21 04:01 UTC, merged