ゲーム中の見た目を変更しました
tricore-as17/scrollShotGame2.5D pull request #20
Opened 2024-06-28 01:04 UTC by tricore-as17

・変更したもの
　・プレイヤーモデル
　・マップチップのデザイン
　・背景画像
![スクリーンショット 2024-06-27 093750](https://github.com/tricore-as17/scrollShotGame2.5D/assets/171524074/3d4de1f6-882a-4f25-a7f6-56700a980bfb)

2024-06-28 06:24 UTC, tricore-as07 requested changes

2024-06-28 06:30 UTC, tricore-as07 commented on GameProject/Colision.h
> +    static bool IsTopHit(const Map& map, const VECTOR& objectPosition, const float objectW, const float objectH, float& fallSpeed, const bool m_isHitTop);
追加でIsTopHitとisHitTopは名前が似すぎていて何を意味するのかがわからないので
どちらかを修正したほうがいいと思います。

2024-06-28 06:47 UTC, tricore-as07 commented
見た目に関してはマップの1マスのわりにプレイヤーが大きすぎるのでそこは調整必須ですね

それからプレイヤーのモデルにだけ光が当たっていて質感に違和感がありますが、
これは後から修正したい項目としてどこかにメモしておいてください

2024-06-28 07:01 UTC, tricore-as17 commented on GameProject/Colision.h
> +    static bool IsTopHit(const Map& map, const VECTOR& objectPosition, const float objectW, const float objectH, float& fallSpeed, const bool m_isHitTop);
引数の方が閲覧用だったのでisHitTopViewOnlyに変更しました。

2024-06-28 07:01 UTC, tricore-as17 commented on GameProject/Map.h
> +    static constexpr int BLANK_CHIP_NUMBER = 452;    //マップタイルの中の空白になっている番号
とりあえず今回のプルリクエストの部分だけ修正しました。
のちほど別のプルリクエストで全体を修正します。

2024-07-01 00:43 UTC, tricore-as07 requested changes

2024-07-01 00:43 UTC, tricore-as07 commented on GameProject/Map.h
> +    int tileGraph = -1;								//マップチップデータの画像
[MUST]
変数宣言とコメント部分の空白にTabが使われているみたいなので修正をお願いします

2024-07-01 00:58 UTC, tricore-as17 commented on GameProject/Colision.h
> +    static bool IsTopHit(const Map& map, const VECTOR& objectPosition, const float objectW, const float objectH, float& fallSpeed, const bool m_isHitTop);
isHItTopViewOnlyでは伝わらないのでisHitTopBeforeFrameに変更しました。

2024-07-01 01:02 UTC, tricore-as17 commented on GameProject/Map.h
> +    int tileGraph = -1;								//マップチップデータの画像
今回のプルリクエストで記載されているファイルのインデントを修正しました。

2024-07-01 01:06 UTC, tricore-as07 approved these changes
LGTM

2024-07-01 01:21 UTC, merged