ショットの見た目を変更しました
tricore-as17/scrollShotGame2.5D pull request #26
Opened 2024-07-08 01:26 UTC by tricore-as17

プレイヤー・通常エネミー・BOSSのショット画像を追加しました

↓プレイヤー
https://github.com/tricore-as17/scrollShotGame2.5D/assets/171524074/51e15d59-9471-48a5-9e7a-439c0280a7db

↓通常エネミー
https://github.com/tricore-as17/scrollShotGame2.5D/assets/171524074/1285c523-b8ce-460c-a50a-7fdc656e6bd5

↓BOSS
https://github.com/tricore-as17/scrollShotGame2.5D/assets/171524074/bc2af7ef-e0ed-4e79-b486-a3d6fd21b525

2024-07-08 06:49 UTC, tricore-as03 requested changes

2024-07-08 06:49 UTC, tricore-as03 commented on GameProject/Player.h
> +    void OrderCreateShot(ShotManager& shotManager);
[MUST]
Playerクラス内でしか呼んでないようなので、publicである必要はないかと。

2024-07-08 06:49 UTC, tricore-as03 commented on GameProject/Player.cpp
> +    if (rotaModelY == MODEL_RIGHT_ROTATION_RATE)
[MUST]
`float`や`double`の浮動小数点を持つ型の==比較はマズいです。
これらの型はプログラムの性質上、演算時に誤差が発生する場合があり、その誤差によりtrueにならない恐れがあります。
https://marycore.jp/prog/c-lang/compare-floating-point-number/#google_vignette
「プレイヤーが左右のどちらを向いているか」の情報をEnum型で別途用意し、その情報をもとに判定を行い、shotDirctionに値を渡す形がようかと。

2024-07-09 00:39 UTC, tricore-as17 commented on GameProject/Player.h
> +    void OrderCreateShot(ShotManager& shotManager);
Playerでしか使用されていないクラスは全てprivateに移動させました！

2024-07-09 00:39 UTC, tricore-as17 commented on GameProject/Player.cpp
> +    if (rotaModelY == MODEL_RIGHT_ROTATION_RATE)
enumを使ってプレイヤーが右を向いているか左を向いているか判断するように変更しました！

2024-07-09 00:44 UTC, tricore-as03 approved these changes
LGTM

2024-07-09 03:32 UTC, merged